<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Geetha" failures="1" tests="5" name="Test" time="51.909" errors="0" timestamp="2023-07-17T05:26:33 PDT">
  <testcase classname="com.test.scripts.TekApiE2E" name="login" time="4.83"/>
  <testcase classname="com.test.scripts.TekApiE2E" name="CreateUser" time="2.678"/>
  <testcase classname="com.test.scripts.TekApiE2E" name="getUsers" time="6.537"/>
  <testcase classname="com.test.scripts.TekApiE2E" name="updateUser" time="20.023"/>
  <testcase classname="com.test.scripts.TekApiE2E" name="deleteUser" time="16.764">
    <failure type="java.lang.AssertionError" message="expected [success] but found [you are not having permission to delete data]">
      <![CDATA[java.lang.AssertionError: expected [success] but found [you are not having permission to delete data]
at com.test.scripts.TekApiE2E.deleteUser(TekApiE2E.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
</testsuite> <!-- Test -->
